apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    name: {{ .Values.name }}
    env: {{ .Values.env }}
  name: {{ .Values.name }}
  namespace: {{ default .Values.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ ternary "letsencrypt-prod" "letsencrypt-staging" (eq .Values.env "prod ") }}
spec:
  rules:
  - host: {{ .Values.name }}.goldspinner.page
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-loadbalancer
            port:
              number: {{ .Values.service.portNumber }}
  tls:
  - hosts:
    - {{ .Values.name }}.goldspinner.page
    secretName: {{ .Values.name }}.goldspinner.page-tls
