app:
  name: sonarr
  image: linuxserver/sonarr
  imageTag: latest
  imagePullPolicy: IfNotPresent
  env: prod

  config:
    # Enables envFrom.configMapRef
    envFrom: true
    # Templates a hostname pod anti-affinity
    podAntiAffinity: false
    # Enables liveness and/or readiness probes
    probes: false

  networking:
    ingress:
      enable: true
      # FQDN for the ingress; also used for httpGet probes
      name: "sonarr.goldspinner.page"
    # Ports for the container, if any
    ports:
      - containerPort: 8989
        name: sonarr
        protocol: TCP

  # Only templated if app.config.probes: true
  probes:
    liveness:
      type: http
      path: /healthz
      port: 8080
    # Uncomment if desired
    #readiness:
    #  type: tcp
    #  port: 80

  # CPU limits are not included by design, but can be added
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi

  persistence:
    # Templates a VolumeClaimTemplate for config, used for StatefulSet
    config:
      enable: true
      storageClassName: "longhorn-retain"
    # Templates an NFS mount
    nfs:
      enable: true
      # The absolute path to the container's NFS mount, e.g. /foo
      mountPath: "/tv"
      serverIP: "192.168.1.202"
      # The absolute path to the server's NFS share, e.g. /export/foo
      serverPath: "/export/tv"
