app:
  name: foobar
  env: dev
  kind: StatefulSet
  image: docker.io/foo:latest
  imagePullPolicy: IfNotPresent

  config:
    # Enables envFrom.configMapRef
    envFrom: true
    # If app.kind: deployment, templates a hostname pod anti-affinity
    podAntiAffinity: true
    # Enables liveness and/or readiness probes
    probes: true
    # If app.kind: deployment, sets replica count
    replicas: 1

  networking:
    ingress:
      enable: true
      # FQDN for the ingress; also used for httpGet probes
      name:
    # Ports for the container, if any
    ports:
      - containerPort: 8080
        name: mysvc
        protocol: TCP

  # Only templated if app.config.probes: true
  probes:
    liveness:
      type: http
      path: /healthz
      port: 8080
    # Uncomment if desired
    #readiness:
    #  type: tcp
    #  port: 80

  # CPU limits are not included by design, but can be added
  resources:
    requests:
      cpu:
      memory:
    limits:
      memory:

  persistence:
    # Templates a VolumeClaimTemplate for config, used for StatefulSet
    config:
      enable: true
      storageClassName: "longhorn-retain"
    # Templates an NFS mount
    nfs:
      enable: true
      # The absolute path to the container's NFS mount, e.g. /foo
      mountPath:
      serverIP:
      # The absolute path to the server's NFS share, e.g. /export/foo
      serverPath:
