apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ .Values.name }}
    env: {{ .Values.env }}
  name: {{ .Values.name }}
  namespace: {{ default .Values.name }}
spec:
  serviceName: {{ .Values.name }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.config.replicas | default "1" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            {{- if (hasKey .Values.resources.limits "cpu") }}
            {{ printf "cpu: %v" .Values.resources.limits.cpu }}
            {{- end }}
            memory: {{ .Values.resources.limits.memory }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-config
        ports:
          - containerPort: {{ .Values.container.targetPortNumber }}
            name: {{ .Values.name }}
            protocol: {{ .Values.container.protocol | default "TCP" }}
      restartPolicy: {{ .Values.deployment.restartPolicy | default "Always" }}
