{{- include "app.header" . }}
{{- include "app.metadata" . }}
spec:
  selector:
    matchLabels:
      name: {{- include "app.name" . }}
  template:
    metadata:
      labels:
        name: {{- include "app.name" . }}
    spec:
      containers:
        {{- include "app.image" . }}
        {{- if .Values.app.config.probes }}
        {{- include "app.probes" . }}
        {{- end }}
        {{- include "app.resources" . }}
        {{- if .Values.app.config.envFrom }}
        {{- include "app.envFrom" . }}
        {{- end }}
        {{- include "app.ports" . }}
        {{- include "app.volumeMounts" . }}
      {{- include "app.volumes" . }}
  {{- include "app.volumeClaimTemplates" . }}
