apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
    env: {{ .Values.env }}
  name: {{ .Values.name }}-config
  namespace: {{ default .Values.name }}
data:
  PGID: {{ .Values.config.pgid | default 1000 }}
  PUID: {{ .Values.config.puid | default 1000 }}
  TZ: {{ .Values.config.tz | default "America/New_York" }}
  UMASK: {{ .Values.config.umask | default "002" }}
