{{- range $name, $data := .Values.jobs -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" $ }}-{{ $name }}
  {{- include "generic.labels" $ | nindent 2 }}
  {{- with $data.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      name: {{ include "app.fullname" $ }}-{{ $name }}
      {{- include "generic.labels" $ | nindent 6 }}
    spec: {{ toYaml $data.spec | nindent 6 }}
{{- end }}