
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "app.fullname" . }}
  {{- include "generic.labels" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      helm.sh/from: deploy.{{ include "app.fullname" . }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
