{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "app.fullname" . }}
  {{- include "generic.labels" . | nindent 2 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
  jobLabel: {{ template "app.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "app.name" . }}
{{- end }}