{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- include "generic.labels" . | nindent 2 }}
{{ with .Values.serviceAccount.labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}