{{- if eq .Values.pods.controller "statefulset" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.fullname" . }}
  {{- include "generic.labels" . | nindent 2 }}
  {{- include "pods.labels" . | nindent 4 }}
  {{- with .Values.pods.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.pods.replicas | default 1 }}
  {{- with .Values.pods.updateStrategy }}
  updateStrategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.pods.minReadySeconds }}
  minReadySeconds: {{ toYaml . | nindent 4 }}
  {{- end }}
  serviceName: {{ include "app.name" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      helm.sh/from: deploy.{{ include "app.fullname" . }}
  template:
    metadata:
      {{- include "generic.labels" . | nindent 6 }}
        helm.sh/from: deploy.{{ include "app.fullname" . }}
        {{- include "pods.podLabels" . | nindent 8 }}
      {{- with .Values.pods.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.pods.dnsPolicy }}
      dnsPolicy: {{ .Values.pods.dnsPolicy }}
      {{- end }}
      {{- with .Values.pods.dnsConfig }}
      dnsConfig: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.priorityClassName }}
      priorityClassName: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.initContainers }}
      initContainers: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "app.name" . }}
          image: "{{ .Values.pods.image.name }}:{{ .Values.pods.image.tag }}"
          imagePullPolicy: {{ .Values.pods.image.pullPolicy }}
          {{- with .Values.pods.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.pods.env }}
          env:
          {{- include "pods.env" . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.envFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.volumeMounts }}
          volumeMounts: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports: {{ toYaml .Values.pods.ports | nindent 12 }}
          resources: {{ toYaml .Values.pods.resources | nindent 12 }}
{{ with .Values.pods.additionalContainers }}{{ toYaml . | indent 8 }}{{ end }}
      {{- with .Values.pods.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.affinity }}
      {{- if .antiAffinity.enabled }}
      affinity:
          {{- if eq .antiAffinity.type "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .antiAffinity.topologyKey }}
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "app.name" $ }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ $.Release.Name }}
          {{- else if eq .antiAffinity.type "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: {{ .antiAffinity.topologyKey }}
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ include "app.name" $ }}
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ $.Release.Name }}
                      app.kubernetes.io/name: {{ include "app.name" $ }}
                      app.kubernetes.io/instance: {{ $.Release.Name }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.pods.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.pods.volumeClaimTemplates }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .nameOverride | default (printf "%s-config" (include "app.name" $ )) }}
      spec:
        accessModes: {{ .accessModes | default (printf "[ %s ]" (quote "ReadWriteOnce")) }}
        storageClassName: {{ required "A StorageClass name is required" .storageClassName }}
        resources:
          requests:
            storage: {{ .storageSize | default "1Gi" }}
  {{- end }}
      {{- with .Values.pods.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
